export const DEFAULT_DISPLAY_LIMIT = 50;
export const COLUMN_WIDTH = 208;
export const COLUMN_GAP = 10;
export const CARD_PADDING = 10;
export const DEFAULT_THUMBNAIL_WIDTH = COLUMN_WIDTH - 2 * CARD_PADDING;
export const DEFAULT_THUMBNAIL_HEIGHT = DEFAULT_THUMBNAIL_WIDTH;
